PROJECT := github.com/juju/utils

check-licence:
	@(fgrep -rl "Licensed under the LGPLv3" .;\
		fgrep -rl "MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT" .;\
		find . -name "*.go") | sed -e 's,\./,,' | sort | uniq -u | \
		xargs -I {} echo FAIL: licence missed: {}

check-go:
ifneq ($(strip $(shell gofmt -l .)),)
	$(error go fmt is sad)
endif
	@(go tool vet -all -composites=false -copylocks=false .)

check: check-licence check-go
	go test $(PROJECT)/...