PROJECT := github.com/juju/utils
GOFMT := $(shell gofmt -l .| sed -e "s/^/ /g")

.PHONY: check-licence check-go check

check: check-licence check-go
	go test $(PROJECT)/...

check-licence:
	@(fgrep -rl "Licensed under the LGPLv3" .;\
		fgrep -rl "MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT" .;\
		find . -name "*.go") | sed -e 's,\./,,' | sort | uniq -u | \
		xargs -I {} echo FAIL: licence missed: {}

check-go:
ifneq ($(strip $(GOFMT)),)
	$(error go fmt is sad: $(GOFMT))
endif
	@(go tool vet -all -composites=false -copylocks=false .)

